# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build the app"
  lane :build do
    xcodebuild(
      project: "App1.xcodeproj",
      scheme: "App1",
      clean: true,
      build: true,
      configuration: "Debug",
      destination: "platform=iOS Simulator,name=iPhone 15,OS=17.4"
    )
  end

  desc "Run tests"
  lane :test do
    xcodebuild(
      project: "App1.xcodeproj",
      scheme: "App1",
      configuration: "Debug",
      destination: "platform=iOS Simulator,name=iPhone 15,OS=17.4",
      test: true
    )
  end
end
